### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by Nomiluks** [clintval/gender-predictor#4]
ImportError                               Traceback (most recent call last)
<ipython-input-1-8688416ad400> in <module>()
----> 1 from gender_predictor import GenderPredictor

anaconda2/lib/python2.7/site-packages/gender_predictor/__init__.py in <module>()
      4 import random as _random
      5 import pickle as _pickle
----> 6 import urllib.request as _request
      7 import collections as _collections

**Comment by clintval** [comment]
This library is a Python 3 port so Python 2.7 is not supported at this time.
